keys:
  - &master age1c3ulr09mhfnrvccm5fu0jc4f9r0wzjlt0smga375ewypjfh8pdsqa43vd9
  - &host_spike age1xfavtxweemc54sh3ty5c8yf3v5nmnad4kwgz9j28j3zu5mw3kg9svdpdr5

creation_rules:
  - path_regex: ^secrets/default\.ya?ml$
    key_groups:
    - age:
      - *master
      - *host_spike
      
  - path_regex: ^secrets/systems/spike\.ya?ml$
    key_groups:
    - age:
      - *master
      - *host_spike
      
  - path_regex: ^secrets/users/adam\.ya?ml$
    key_groups:
    - age:
      - *master
      - *host_spike

