master:
    key: ENC[AES256_GCM,data:OyeIrYIdKMHdAeFM4F3iyd9EDfQO7P0a5/VUtwuFd0dWsd80l7A67BLfkLUlvg0TxSggO9WFKnriipMrTIHF+1kW/H5P3r5KRNw=,iv:mdEMhivf4Xe/mZMBnvnWqVl8yTHbl/sYNUZAf9ekYCg=,tag:Ir1lpPi2OBcT6JgchIBTWw==,type:str]
    pub: ENC[AES256_GCM,data:BEJrmuRQybAWuXZxNllnxChA5bAzC35hDjFFNxlvse7i9qnPaMn/QsZtFHozRGXpmaJ93zyhlx6wt8MkBvM=,iv:rBEU9Cc5TwJ8Q5rqan3TR7xwT9dUCpOhFaY/LEbl7YY=,tag:vJOUlu7L7ZnSQBtXS/GNPg==,type:str]
ts_auth:
    id: ENC[AES256_GCM,data:BCuLYphfYBb3WhVoAGBP1L0=,iv:RdE2Xztuk5xPLPLd1Ds8a8v9BYANvPI96+7lo4DcOTE=,tag:Evp8dR9wuOd5fY0pUeCx4A==,type:str]
    secret: ENC[AES256_GCM,data:22LFRqoB6kln3HWWWpDZkbRzQ1YT/0knBpljVYLEcSuMyxWrEAZpQCkEYE7jSrzKZOgY6E2+cxhpYAPu8aOT,iv:HdhDxTjgctC4HuTCiSjkqOY7izU/B+P3F6qxCC3fIsM=,tag:nXFUm2zx1KVbjmlphwEbAA==,type:str]
sops:
    age:
        - recipient: age1c3ulr09mhfnrvccm5fu0jc4f9r0wzjlt0smga375ewypjfh8pdsqa43vd9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtS1J4WTBxVGVPTFBBU2FH
            enFQN1lYS3FacjJYMzlVMXdKaUQzZzBORWs0CklvNXhsanNueEtEVk9pc0wwS2tJ
            SjBnQmdjWDFKOXFvRUFYUVJTUGNobGMKLS0tIHc4YWI4YURqWW1BNElRaGdqTUpU
            eGF3akk4Z3ZvQXBTQVhuVFNWVjA1bGsKw/mQGy79JvHUU78EsvkRBGPeNFCAyy35
            VWMANvdlskHwvnYEuXrXOS1lK/2G6G6P/ZiAqv0xTsWHT6mCYXQjyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfavtxweemc54sh3ty5c8yf3v5nmnad4kwgz9j28j3zu5mw3kg9svdpdr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q0FSZ3M4UzBHNGhsaXd0
            YzZKS1B1MFhiOC9vNURHSzc1Q3BaSll0bEdrCmpTSXZuM1VGWHR0dzI5NGg4N3hs
            VU5DYnpPa3dHOGI4TmNKUm1PZi9PL1EKLS0tIC9ObVRwNCtTbUF2UXVjNWp4Rncy
            NjQ5bGt1Z25qTEJRQ2pSMm9oRGNhcjAK6lOgiEp/M+rcQxzdq6oNHqrNfBOqSd76
            axCLNnYZc2Tv75yzAzrmIhMKtGwBrtuWn3tI0iJNkVSZDrCezjC1qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T18:51:51Z"
    mac: ENC[AES256_GCM,data:7SJH9Vfa5JKJSXdM+ToCFPFqDyYu1eBAe2FsssW4Z5IsR49re9DxeNz3MU4hQL/UVQhmwYBGeFU07Sxq2dIZhun8UICrRRDcDogW24qR1P+9Konuxy76LXUd/y11wIf9KWdF9YmNzg0jIZQB15rD1gJ3+VUJAlj+KYh61doFHFI=,iv:5FeHfAQic2ezQoRazjhuURtjUYvUfaYFgSejflfOQFk=,tag:sHDF/66b+i1hNVS2ZhrccA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
