test: ENC[AES256_GCM,data:7lyv/q7puw==,iv:Jb+ca+vi6kyxPq9m0ESguH32TgjXwSNM6+zw509XWO8=,tag:fasrVddqBuG2wd2DZtv9rQ==,type:str]
sops:
    age:
        - recipient: age1xfavtxweemc54sh3ty5c8yf3v5nmnad4kwgz9j28j3zu5mw3kg9svdpdr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNjk3ODFWenZ1SEJ5dFBm
            aXREVFZHMUU4Z3dqbTJSeVRVSkh3VnQzNlE0CjlickpiNjhVYmlaVU5RTG55SFli
            K0toL1BSZExYR3NuUS9qK0dVYllzQWMKLS0tIGdKQzZQcXBoVjdsV200MmlIWnI5
            YXV5VnRWbkxSZEY5NVFvcDUva1JHQ1kK6w+eq3+w+jsRIqQYAwXb8sPEn6kOqY+t
            ZKwP6K4W/vLFDEfiA+wwk7nj1Pia7hLuKSiIbNh2KGwGZEnAzg3Pfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T18:09:05Z"
    mac: ENC[AES256_GCM,data:bKkTcpf/w81yRvOmVTHml0JOwF41QYzCr4loexJ0AaJFtNQlCIEnwty71q64QsPe2QZuvg6e6p4s1h31BuVo/tVrVfffubfifzD7T0U0WsFbytEONluoEyTs0zx22/oDKRPabWo6heJba7bpc/AAi6ybZiauSvsgx4gs2s3ZJlk=,iv:shDS1KSPIfu+idBOd5PjXIwUMKIGoGHElU4wbacxe48=,tag:OdR4BwGTsKp0nR4G2KEdgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
